---
- hosts: all
  become: yes

  tasks:
    - debug: 
        msg: "Now that the updates will begin, 
              Ubuntu 14.04.2 -> Ubuntu 14.04.6"

- name: Start Key Exchange ------------
  include: key_exchange.yml

- name: Start Update ------------------
  include: ubuntu_update.yml
